name: Build Family Mate APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Accept Android licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
      
    - name: Create Android project structure
      run: |
        # Create directories
        mkdir -p app/src/main/java/com/familymate/app
        mkdir -p app/src/main/res/values
        mkdir -p gradle/wrapper
        
        # Create MainActivity.java
        cat > app/src/main/java/com/familymate/app/MainActivity.java << 'EOF'
        package com.familymate.app;
        import android.app.Activity;
        import android.os.Bundle;
        import android.webkit.WebView;
        import android.webkit.WebSettings;
        import android.webkit.WebViewClient;
        
        public class MainActivity extends Activity {
            @Override
            protected void onCreate(Bundle savedInstanceState) {
                super.onCreate(savedInstanceState);
                
                WebView webView = new WebView(this);
                WebSettings webSettings = webView.getSettings();
                webSettings.setJavaScriptEnabled(true);
                webSettings.setDomStorageEnabled(true);
                
                webView.setWebViewClient(new WebViewClient());
                webView.loadUrl("https://family-mate-demo.replit.app");
                
                setContentView(webView);
            }
        }
        EOF
        
        # Create AndroidManifest.xml
        cat > app/src/main/AndroidManifest.xml << 'EOF'
        <manifest xmlns:android="http://schemas.android.com/apk/res/android"
            package="com.familymate.app">
            
            <uses-permission android:name="android.permission.INTERNET" />
            
            <application android:label="Family Mate">
                <activity android:name=".MainActivity"
                    android:exported="true">
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN" />
                        <category android:name="android.intent.category.LAUNCHER" />
                    </intent-filter>
                </activity>
            </application>
        </manifest>
        EOF
        
        # Create build files
        cat > app/build.gradle << 'EOF'
        apply plugin: 'com.android.application'
        
        android {
            compileSdkVersion 33
            defaultConfig {
                applicationId "com.familymate.app"
                minSdkVersion 21
                targetSdkVersion 33
                versionCode 1
                versionName "1.0"
            }
            buildTypes {
                release {
                    minifyEnabled false
                }
            }
        }
        EOF
        
        cat > build.gradle << 'EOF'
        buildscript {
            repositories {
                google()
                mavenCentral()
            }
            dependencies {
                classpath 'com.android.tools.build:gradle:7.4.2'
            }
        }
        allprojects {
            repositories {
                google()
                mavenCentral()
            }
        }
        EOF
        
        echo "include ':app'" > settings.gradle
        
        # Create gradle wrapper
        curl -s https://raw.githubusercontent.com/gradle/gradle/v7.6.1/gradlew > gradlew
        chmod +x gradlew
        
    - name: Build APK
      run: ./gradlew assembleRelease
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: family-mate-apk
        path: app/build/outputs/apk/release/app-release-unsigned.apk
