name: Build Family Mate APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js  
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
        
    - name: Install Cordova
      run: npm install -g cordova
        
    - name: Create Cordova app
      run: |
        cordova create familymate com.familymate.app "Family Mate"
        cd familymate
        
        # Simple HTML for your app
        cat > www/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Family Mate</title>
            <style>
                body { margin: 0; padding: 20px; font-family: Arial, sans-serif; background: #f5f5f5; }
                .container { max-width: 400px; margin: 0 auto; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
                h1 { color: #FF6B9D; text-align: center; margin-bottom: 20px; }
                .feature { margin: 15px 0; padding: 10px; background: #f9f9f9; border-radius: 5px; }
                .feature strong { color: #4ECDC4; }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>Family Mate</h1>
                <p style="text-align: center; color: #666;">Complete family organization app</p>
                
                <div class="feature">
                    <strong>👥 Family Management:</strong> Track all family members with photos and roles
                </div>
                
                <div class="feature">
                    <strong>📅 Smart Calendar:</strong> Color-coded activities and appointments
                </div>
                
                <div class="feature">
                    <strong>📥 Import Appointments:</strong> CSV and ICS calendar file support
                </div>
                
                <div class="feature">
                    <strong>🍽️ Meal Planning:</strong> Plan breakfast, lunch, and dinner
                </div>
                
                <div class="feature">
                    <strong>✅ Task Management:</strong> Assign and track family tasks
                </div>
                
                <p style="text-align: center; margin-top: 30px; color: #FF6B9D;"><strong>Perfect for busy families to stay organized!</strong></p>
            </div>
        </body>
        </html>
        EOF
        
        cordova platform add android
        
    - name: Build APK
      run: |
        cd familymate
        cordova build android --release
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: family-mate-apk
        path: familymate/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
